In [9]:
import torch
import rich
from rich import print
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%load_ext rich

The rich extension is already loaded. To reload it, use:
  %reload_ext rich


<div class="jumbotron">
    <h1 class="display-1">数据操作</h1>
    <hr class="my-4">
    <p>主讲：李岩</p>
    <p>管理学院</p>
    <p>liyan@cumtb.edu.cn</p>
</div>

\begin{definition}\label{def:tensor}
张量（Tensor）：$n$维数组
\end{definition}

- 张量与`Numpy`的$n$维数组类似，`ndarray`
    - 具有一个轴的张量对应数学上的向量（vector）
    - 具有两个轴的张量对应数学上的矩阵（matrix）

- 张量具有的独特功能：
    - 支持GPU运算
    - 支撑自动微分

## 创建张量

### 一维张量

```python
import torch
torch.arange(start=0,end,step=1)
```
- 默认创建为整数
- `start`、`end`、`step`中，任何一个为浮点型，创建的张量也是浮点型

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x1 = torch.arange(1,2.5,0.5)
x1

tensor([1.0000, 1.5000, 2.0000])

### 张量的形状与元素数量

- 可以通过张量的`shape`属性访问张量（沿每个轴）的形状


In [5]:
x.shape

torch.Size([12])

- 如果只想知道张量中元素的总数，即形状的所有元素**乘积**，可以检查它的大小（size）
- 利用张量的`numel()`方法


In [6]:
x.numel()

12

### 改变张量的形状

- 要想改变一个张量的形状而不改变元素数量和元素值，可以调用`reshape`函数
    - 例如，把张量`x`从形状为（12,）的行向量转换为形状为（3,4）的矩阵

In [7]:
X = x.reshape(3, 4)
X


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

- 在指定若干维度后，可以用$-1$自动计算剩余维度
    - 例如用`x.reshape(-1,4)`或`x.reshape(3,-1)`来取代`x.reshape(3,4)`

In [10]:
X1 = x.reshape(-1,4)
X2 = x.reshape(3,-1)
print(f'X1 {X1}')
print(f'X2 {X2}')

X1 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

X2 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### 创建特殊张量

#### 创建全0张量

In [11]:
X3 = torch.zeros((2, 3, 4))
X3


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
print(f'X3的形状是 {X3.shape}')
print(f'X3的元素数量是 {X3.numel()}')

X3的形状是 torch.Size([2, 3, 4])

X3的元素数量是 24

#### 创建全1张量

In [14]:
X4 = torch.ones((2, 3, 4))
X4


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

#### 创建随机抽样的张量

- 通过从某个特定的概率分布中随机采样得到张量中每个元素的值
    - 创建一个形状为（3,4）的张量，每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样


In [15]:
X5 = torch.randn(3, 4)
X5


tensor([[ 0.0026,  1.4230,  0.7207,  1.4187],
        [-0.0348,  0.1922, -0.5013, -1.2898],
        [-1.3458,  1.3705,  0.1110,  1.0360]])

### 通过列表（或嵌套列表）创建张量

- 最外层的列表对应于轴0，内层的列表对应于轴1，依次类推

In [19]:
X6 = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X6
X6.shape


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

torch.Size([3, 4])

In [18]:
X7 = torch.tensor([[[1,2,2,1],[3,4,4,3]],[[5,6,6,5],[7,8,8,7]],[[9,10,10,9],[11,12,12,11]]])
X7
X7.shape


tensor([[[ 1,  2,  2,  1],
         [ 3,  4,  4,  3]],

        [[ 5,  6,  6,  5],
         [ 7,  8,  8,  7]],

        [[ 9, 10, 10,  9],
         [11, 12, 12, 11]]])

torch.Size([3, 2, 4])

## 运算符

### 按元素（elementwise）运算

- 将标准标量运算符应用于数组的每个元素

- 对于将两个数组作为输入的函数，按元素运算将二元运算符应用于两个数组中的每对位置对应的元素

- 对于任意具有**相同形状的张量**，常见的标准算术运算符（`+`、`-`、`*`、`/`和`**`）都可以被升级为按元素运算

In [20]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y


(
    tensor([ 3.,  4.,  6., 10.]),
    tensor([-1.,  0.,  2.,  6.]),
    tensor([ 2.,  4.,  8., 16.]),
    tensor([0.5000, 1.0000, 2.0000, 4.0000]),
    tensor([ 1.,  4., 16., 64.])
)

### 张量的连结（concatenate）

- 需要提供张量列表，并给出沿**哪个轴**连结

```python
torch.cat(tensors,dim=0)
```
- `tensors`：具有相同形状的张量的序列
- `dim`：连结张量沿的轴

In [21]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(f'X {X}')
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(f'Y {Y}')

X tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Y tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [22]:
print(f'X,Y沿轴0连结\n{torch.cat((X, Y), dim=0)}')

X,Y沿轴0连结
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [24]:
print(f'X,Y沿轴1连结\n{torch.cat((X, Y), dim=1)}')

X,Y沿轴1连结
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

### 对张量中的所有元素求和


In [25]:
X.sum()

tensor(66.)

## 广播机制（broadcasting mechanism）

- 在形状不同的两个张量上通过调用*广播机制*执行按元素操作

- 这种机制的工作方式如下：

    - 通过适当复制元素扩展一个或两个数组，使得在转换之后，两个张量具有**相同的形状**
    - 对生成的数组执行按元素操作

> 在大多数情况下将沿着数组中**长度为1的轴**进行广播

In [26]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(f'a为\n{a}')
print(f'b为\n{b}')

a为
tensor([[0],
        [1],
        [2]])

b为
tensor([[0, 1]])

In [27]:
a + b


tensor([[0, 1],
        [1, 2],
        [2, 3]])

\begin{problem}\label{prob:cat}
如果两个张量没有轴的长度为1，张量相加会出现什么结果？
\end{problem}

In [29]:
c = torch.arange(6).reshape(3,2)
d = torch.arange(8).reshape(4,2)
c
d


tensor([[0, 1],
        [2, 3],
        [4, 5]])


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [30]:
c+d

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

## 索引和切片

### 访问张量的元素

- 张量中的元素可以通过索引访问
- 第一个元素的索引是0（正向索引），最后一个元素索引是-1（反向索引）

In [31]:
X


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
print(f'X的最后一个元素为\n{X[-1]}')
print(f'X的后两个元素为\n{X[1:3]}')

X的最后一个元素为
tensor([ 8.,  9., 10., 11.])

X的后两个元素为
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [34]:
X[:,-1] # 在轴1上取元素

tensor([ 3.,  7., 11.])

### 更改张量的元素

- 通过指定索引将元素写入张量


In [35]:
X[1, 2] = 9
print(f'更改后的X为\n{X}')

更改后的X为
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
X[0:2, :] = 12
print(f'更改后的X为\n{X}')

更改后的X为
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 节省内存

- 运行一些操作可能会导致为新结果分配内存
    - 例如，如果用`Y = X + Y`，新的`Y`会指向新分配的内存处的张量

In [50]:
Z = torch.zeros_like(Y)  # 创建与Y具有相同形状的全零张量
print(f'id(Z): {id(Z)}')
Z = Z + Y
print(f'id(Z): {id(Z)}')

id(Z): 140686062351280

id(Z): 140686062343408

- 基于下面两个原因上述做法不可取：

    - 不想总是不必要地分配内存。机器学习可能有数百兆的参数，并且在一秒内多次更新所有参数。通常情况下，希望原地执行这些更新
    - 如果不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数


- **执行原地操作**的方法：
    - 使用切片表示法将操作的结果分配给先前分配的数组，例如`Y[:] = <expression>`

- 如果在后续计算中没有重复使用`X`，也可以使用`X[:] = X + Y`或`X += Y`来减少操作的内存开销

In [51]:
id(Z)
Z[:] = Z+Y
id(Z)

140686062343408

140686062343408

In [52]:
id(Z)
Z += Y
id(Z)

140686062343408

140686062343408

## 转换为其他Python对象


- 深度学习框架定义的张量与Numpy数组（`ndarray`）可以相互转换

In [54]:
A = X.numpy()   # 将torch的张量转换为Numpy的数组
B = torch.tensor(A)  # 将Numpy的数组转换为torch的张量
print(f'A的数据类型为{type(A)}')
print(f'B的数据类型为{type(B)}')

A的数据类型为<class 'numpy.ndarray'>

B的数据类型为<class 'torch.Tensor'>

- 将**大小为1的张量**转换为Python标量，可以调用张量的`item`函数或Python的内置函数实现


In [55]:
a = torch.tensor([3.5])
a

tensor([3.5000])

In [56]:
print(f'通过张量的item函数，{a.item()}')
print(f'通过Python内置的float函数，{float(a)}')
print(f'通过Python内置的int函数，{int(a)}')

通过张量的item函数，3.5

通过Python内置的float函数，3.5

通过Python内置的int函数，3